name: Yeah
favicon: null
layout_spectrum: 0.8128617722541094
typography_spectrum: 0.7160096641164273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7652522125281394
  lightness: 0.5378357076551765
  saturation: 0.22301264712587
  rhythmicContrast: 0.9678258118219674
purpose: []
